### PR TITLE
Manually add building for py3

### PR DESCRIPTION
**Pull request by johannesring**

### CODE REVIEW

**Comment by johannesring** [comment]
@jakirkham, @scopatz - Any idea why this is not included when re-rendering libadjoint? Is it my system that is broken or can you reproduce this on your setup? I see the same problem when re-rendering [fenics](https://github.com/conda-forge/fenics-feedstock), while other packages seems to work fine.

**Comment by scopatz** [comment]
Probably because the dependencies haven't been rerendered and made it up to anaconda.org yet

**Comment by johannesring** [comment]
Thanks @scopatz. Maybe you are right, but in that case, would all checks have passed like they have here?

**Comment by scopatz** [comment]
Probably because the rerender wouldn't have picked them up.

**Comment by jakirkham** [comment]
> Any idea why this is not included when re-rendering libadjoint? Is it my system that is broken or can you reproduce this on your setup? I see the same problem when re-rendering [fenics](https://github.com/conda-forge/fenics-feedstock), while other packages seems to work fine.

Sorry, I'm unclear. What exactly is it we are looking at?

**Comment by johannesring** [comment]
Thanks for looking at this and sorry for being unclear. The problem is that after running `conda smithy rerender` I see the following changes:
``` diff
$ git diff --staged
diff --git a/.travis.yml b/.travis.yml
index e4ca552..8dc9620 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -7,12 +7,6 @@ os: osx
 osx_image: beta-xcode6.1
 
 env:
-  matrix:
-    
-    - CONDA_PY=27
-    - CONDA_PY=34
-    - CONDA_PY=35
-    - CONDA_PY=36
   global:
     # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
     - secure: "kbWXCSVo0YB/OUTld4wwfARSgihLPDSKJ8arwZBzcLM6ZHNm6+SXa0Y2IU9SLC5pyyicZbN2vxuDWgi0MKdLsYWwfDHo0bmJi3Gv8tvmGzJXYpViXOfubHv5cQcGJrUZ75JpW/FicdmsGYhKVGwY1As0ucJW0ZfF9m9m3xDMrmWuEkM+iRjrirDxbbAsoK0e0r1HdEFk/4KiWwXqqNYiu16PJm/pN7SyuQbKwN0BH7Yu70yXBrMCPcz0ZNitBOZOb37vbmGlI00lKB4jD+E0mj+J1/c47h71qaK0ApAQyqAMgaueo5uqQrQwK0A7dTRgkP3Nlw/xFKsbEBbmgH6cFXV5FyOLcGy2SRLM62HwOiwnDqtjCK5Nbe/Gupqz65+tfP7O8EtAK9vRx3FYK044dIsG4W5qRI1eWfcsvztiuzbumpLJz2KdReZPQRTOIKS/eY/FpXnK5elepJH2XtAnPPzf+6Vcfrzl+ypLfcNFaY9cVWSBIYHeHkyQvxpvJVvKN0PgH2P/Yn+AcMV+PMNDx9+k3JymUtUVk77ju0q064Hzn4gy7GsCpumTfZebzmKWZnlGI8M9gJ55UpTYlabYJxjT/hLiUwZTZHZk+UZ7YjImPKVp5DZsGDoZYJhCSKyxDHRP9MruWqTomI28u/bTYgWwx7fTtFDBXRVZdgnQCY0="
diff --git a/ci_support/run_docker_build.sh b/ci_support/run_docker_build.sh
index 134dd8c..f4bad78 100755
--- a/ci_support/run_docker_build.sh
+++ b/ci_support/run_docker_build.sh
@@ -41,28 +41,7 @@ conda clean --lock
 conda install --yes --quiet conda-forge-build-setup
 source run_conda_forge_build_setup
 
-# Embarking on 4 case(s).
-    set -x
-    export CONDA_PY=27
-    set +x
-    conda build /recipe_root --quiet || exit 1
-    upload_or_check_non_existence /recipe_root conda-forge --channel=main || exit 1
-
-    set -x
-    export CONDA_PY=34
-    set +x
-    conda build /recipe_root --quiet || exit 1
-    upload_or_check_non_existence /recipe_root conda-forge --channel=main || exit 1
-
-    set -x
-    export CONDA_PY=35
-    set +x
-    conda build /recipe_root --quiet || exit 1
-    upload_or_check_non_existence /recipe_root conda-forge --channel=main || exit 1
-
-    set -x
-    export CONDA_PY=36
-    set +x
+# Embarking on 1 case(s).
     conda build /recipe_root --quiet || exit 1
     upload_or_check_non_existence /recipe_root conda-forge --channel=main || exit 1
 EOF
```
I have added these lines back manually in this PR.

**Comment by jakirkham** [comment]
That is very disconcerting. FWIW I checked out this repo locally. After re-rendering, it added back the Python versions. There isn't anything about the dependencies that would make sense of this nor of this recipe itself. Could you please raise an issue on `conda-smithy`? We can discuss more and try to figure out the cause of this change.

**Comment by johannesring** [comment]
@jakirkham - I have filed an issue now: https://github.com/conda-forge/conda-smithy/issues/429.

**Pull request merged**
